/**
 * User model
 * @module user/model
 */

const uuid = require('uuid');

/**
 * User instance type
 * @typedef {Object} User
 * @property {String} id user id
 * @property {String} name user name
 * @property {String} login user login
 * @property {String} password user password
 */

/** Class representing a task */
class User {
  /**
   * @type {User}
   * @param {userProps} [props] object containing user properties
   * @param {String} [props.id] user id (auto-generated by uuid by default)
   * @param {String} [props.name="USER"] user name
   * @param {String} [props.login="user"] user login
   * @param {String} [props.password="P@55w0rd"] user password
   */
  constructor({
    id = uuid.v4(),
    name = 'USER',
    login = 'user',
    password = 'P@55w0rd',
  } = {}) {
    this.id = id;
    this.name = name;
    this.login = login;
    this.password = password;
  }

  /**
   * Strips provided userInstance to basic properties and returns a JS object without password
   * @param {User} userInstance user instance
   * @returns {Object} simple JavaScript object without password field
   */
  static toResponse(user) {
    const { id, name, login } = user;

    return { id, name, login };
  }
}

module.exports = User;
