/**
 * User model
 * @module user/model
 */

const uuid = require('uuid');

/**
 * A JavaScript object containing properties for the User instance
 * @typedef {Object} userProps
 * @property {String} [id] - User id (auto-generated by uuid by default)
 * @property {String} [name="USER"] - User name
 * @property {String} [login="user"] - User login
 * @property {String} [password="P@55w0rd"] - User password
 */

/** Class representing a task */
class User {
  /**
   * @param {userProps} [params]
   */
  constructor({
    id = uuid.v4(),
    name = 'USER',
    login = 'user',
    password = 'P@55w0rd',
  } = {}) {
    /**
     * @property {String} id - user id
     */
    this.id = id;
    /**
     * @property {String} name - user name
     */
    this.name = name;
    /**
     * @property {String} login - user login
     */
    this.login = login;
    /**
     * @property {String} password - user password
     */
    this.password = password;
  }

  /**
   * Strips provided userInstance to basic properties and returns a JS object without password
   * @param {User} userInstance - an instance of User class
   * @returns {Object} - a simple JavaScript object without password
   */
  static toResponse(user) {
    const { id, name, login } = user;

    return { id, name, login };
  }
}

module.exports = User;
