version: '3.8'
services:
  app:
    build: .
    env_file: .env
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./log:/app/log
      - ./src:/app/src
    networks:
      - usernet

  db:
    build: ./db/
    env_file: .env
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - usernet

networks:
  usernet:
    driver: bridge

volumes:
  db-data:
