version: '3.8'
services:
  app:
    container_name: app
    build: .
    command: npm run dev
    image: vasiliz/rss-node-js-2021-q2:app
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./log:/usr/app/log
      - ./src:/usr/app/src
    networks:
      - app-bridge
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST_DOCKER}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_SYNC: ${DB_SYNC}
      DB_LOGGING: ${DB_LOGGING}

  db:
    container_name: db
    build: 
      context: .
      dockerfile: Dockerfile.database
    image: postgres:13.3-alpine
    restart: always
    ports:
      - ${DB_OUTER_PORT}:${DB_PORT}
    volumes:
      - pgdata:${DOCKER_DB_DATA}
    networks:
      - app-bridge
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_HOST: ${DB_HOST_DOCKER}
      PGDATA: ${DOCKER_DB_DATA}

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - app-bridge
    logging:
      driver: none
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

networks:
  app-bridge:
    driver: bridge

volumes:
  pgdata:
  pgadmin:
