version: '3.8'
services:
  app:
    build: .
    env_file: .env
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./log:/usr/app/log
      - ./src:/usr/app/src
    networks:
      - app-bridge

  db:
    build: ./db/
    env_file: .env
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-bridge

networks:
  app-bridge:
    driver: bridge

volumes:
  db-data:
