version: '3.8'
services:
  app:
    build: .
    command: npm run dev
    image: vasiliz/rss-node-js-2021-q2:app
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./log:/usr/app/log
      - ./src:/usr/app/src
    networks:
      - app-bridge
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_SYNC: ${DB_SYNC}
      DB_LOGGING: ${DB_LOGGING}

  db:
    build: ./db/
    image: postgres:13.3-alpine
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-bridge
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
      PGDATA: ${DOCKER_DB_DATA}

networks:
  app-bridge:
    driver: bridge

volumes:
  db-data:
