/**
 * Board model
 * @module board/model
 */
const uuid = require('uuid');
//
const Column = require('./column.model');

/**
 * A JavaScript object containing properties for the Board instance
 * @typedef {Object} boardProps
 * @property {String} [id] board id (auto-generated by uuid by default)
 * @property {String} [title = 'Board Title'] board title
 * @property {Array<Column>} [columns = [Column]] board columns
 */

/** Class representing a board */
class Board {
  /**
   * Creates a Board instance
   * @param {boardProps} [props={}] object containing board properties
   * @property {String} id board id
   * @property {String} title board title
   * @property {Array<Column>} columns an array of Column instances
   */
  constructor({
    id = uuid.v4(),
    title = 'Board Title',
    columns = [new Column()],
  } = {}) {
    this.id = id;
    this.title = title;
    this.columns = columns;
  }
}

module.exports = Board;
