/**
 * Column model
 * @module board/model
 * @ignore
 */
const uuid = require('uuid');

/**
 * A JavaScript object containing properties for the Column instance
 * @typedef {Object} columnProps
 * @property {String} [id] column id (auto-generated by uuid by default)
 * @property {String} [title="Column Title"] column title
 * @property {Number} [order=0] - order of this Column on the Board
 */

/** Class representing a column */
class Column {
  /**
   * Creates a column instance
   * @param {columnProps} [props] - an object containing Column properties
   * @property {String} id - column id
   * @property {String} title - column title
   * @property {Number} order - column order
   */
  constructor({ id = uuid.v4(), title = 'Column Title', order = 0 } = {}) {
    this.id = id;
    this.title = title;
    this.order = order;
  }
}

module.exports = Column;
